version: 2
jobs:
  build:
    working_directory: ~/docker-webhook
    docker:
      - image: circleci/golang:1.11-stretch-node
        environment:
          IMAGE_NAME: docker-webhook
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Build docker image
        command: |
          docker build --rm=false -t docker-webhook:build .
    - run:
        name: Export docker image
        command: |
          docker save -o /tmp/image.tar docker-webhook:build

    - run:
        name: Store git revision data
        command: |
          git rev-parse --verify  HEAD > /tmp/git-rev-parse.txt
          git describe --tags --always > /tmp/git-rev-tags.txt
          echo rev-parse: $(cat /tmp/git-rev-parse.txt)
          echo describe: $(cat /tmp/git-rev-tags.txt)

    - persist_to_workspace:
        name: Store docker image
        root: /tmp
        paths:
        - image.tar
        - git-rev-parse.txt
        - git-rev-tags.txt

  push_latest:
    working_directory: ~/docker-webhook
    docker:
    - image: circleci/python:3.6.1
      environment:
        IMAGE_NAME: docker-webhook
    steps:
    - setup_remote_docker
    - attach_workspace:
        at: tmp
    - run:
        name: Load docker image
        command: |
          docker load -i tmp/image.tar

    - checkout:
        path: repo


    - run:
        name: Install the AWS CLI
        command: |
          python3 -m venv venv
          . venv/bin/activate
          ls -al
          ls -al ../

          ls -al tmp/
          pip install -r repo/.circleci/requirements.txt

    - run:
        name: Docker login
        command: |
          . venv/bin/activate
          eval $(AWS_ACCESS_KEY_ID=$ECR_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$ECR_AWS_SECRET_ACCESS_KEY  aws ecr get-login --region $ECR_AWS_REGION --no-include-email)

    - run:
        name: Tag image
        command: |
          docker tag docker-webhook:build $AWS_DOCKER_REGISTRY/$IMAGE_NAME:latest
          docker tag docker-webhook:build $AWS_DOCKER_REGISTRY/$IMAGE_NAME:$(cat tmp/git-rev-parse.txt)

    - run:
        name: Push images
        command: |
          docker push $AWS_DOCKER_REGISTRY/$IMAGE_NAME:$(cat tmp/git-rev-parse.txt)
          docker push $AWS_DOCKER_REGISTRY/$IMAGE_NAME:latest

  push_tagged:
    working_directory: ~/docker-webhook
    docker:
    - image: circleci/python:3.6.1
      environment:
        IMAGE_NAME: docker-webhook
    steps:
    - setup_remote_docker
    - attach_workspace:
        at: tmp

    - checkout:
        path: repo


    - run:
        name: Install the AWS CLI
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r repo/.circleci/requirements.txt

    - run:
        name: Load docker image
        command: |
          docker load -i tmp/image.tar

    - run:
        name: Docker login
        command: |
          . venv/bin/activate
          eval $(AWS_ACCESS_KEY_ID=$ECR_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$ECR_AWS_SECRET_ACCESS_KEY  aws ecr get-login --region $ECR_AWS_REGION --no-include-email)

    - run:
        name: Tag image
        command: |
          docker tag docker-webhook:build $AWS_DOCKER_REGISTRY/$IMAGE_NAME:$(cat tmp/git-rev-tags.txt)

    - run:
        name: Push images
        command: |
          docker push $AWS_DOCKER_REGISTRY/$IMAGE_NAME:$(cat tmp/git-rev-tags.txt)

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - push_latest:
          requires:
            - build
          filters:
            branches:
              only: master
      - push_tagged:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
