version: 2
jobs:
  build:
    #working_directory: /tmp/docker-webhook
    docker:
      - image: circleci/golang:1.11-stretch-node
        environment:
          IMAGE_NAME: docker-webhook
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Build docker image
        command: |
          docker build --rm=false -t docker-webhook:build .

    - run:
        name: Login to artifactory
        command: |
          echo "$ARTIFACTORY_PASSWORD" | docker login -u $ARTIFACTORY_USER --password-stdin $DOCKER_PRIVATE_REPO

    - run:
        name: Tag image
        command: |
          docker tag docker-webhook:build $DOCKER_PRIVATE_REPO/$IMAGE_NAME:latest
          docker tag docker-webhook:build $DOCKER_PRIVATE_REPO/$IMAGE_NAME:$(git describe --tags --always)
          docker tag docker-webhook:build $DOCKER_PRIVATE_REPO/$IMAGE_NAME:$(git rev-parse --verify  HEAD)

    - run:
        name: Push images
        command: |
          docker push $DOCKER_PRIVATE_REPO/$IMAGE_NAME:$(git describe --tags --always)
          docker push $DOCKER_PRIVATE_REPO/$IMAGE_NAME:$(git rev-parse --verify  HEAD)
          docker push $DOCKER_PRIVATE_REPO/$IMAGE_NAME:latest


workflows:
  version: 2
  build_and_upload:
    jobs:
      - build:
          filters:
            branches:
              only:
                - "master"
            tags:
              only:
                - "/.*/"