version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11-stretch-node
        environment:
          IMAGE_NAME: docker-webhook
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Build docker image
        command: |
          docker build --rm=false -t docker-webhook:build .
    - run:
        name: Export docker image
        command: |
          docker save -o /tmp/image.tar docker-webhook:build

    - run:
        name: Store git revision data
        command: |
          git rev-parse --verify  HEAD > /tmp/git-rev-parse.txt
          git describe --tags --always > /tmp/git-rev-tags.txt
          echo rev-parse: $(cat /tmp/git-rev-parse.txt)
          echo describe: $(cat /tmp/git-rev-tags.txt)

    - persist_to_workspace:
        name: Store docker image
        root: /tmp
        paths:
        - image.tar
        - git-rev-parse.txt
        - git-rev-tags.txt

  push_latest:
    docker:
    - image: circleci/golang:1.11-stretch-node
      environment:
        IMAGE_NAME: docker-webhook
    steps:
    - setup_remote_docker
    - attach_workspace:
        at: tmp
    - run:
        name: Load docker image
        command: |
          docker load -i tmp/image.tar

    - run:
        name: Login to artifactory
        command: |
          echo "$ARTIFACTORY_PASSWORD" | docker login -u $ARTIFACTORY_USER --password-stdin $DOCKER_PRIVATE_REPO


    - run:
        name: Tag image
        command: |
          docker tag docker-webhook:build $DOCKER_PRIVATE_REPO/$IMAGE_NAME:latest
          docker tag docker-webhook:build $DOCKER_PRIVATE_REPO/$IMAGE_NAME:$(cat tmp/git-rev-parse.txt)

    - run:
        name: Push images
        command: |
          docker push $DOCKER_PRIVATE_REPO/$IMAGE_NAME:$(cat tmp/git-rev-parse.txt)
          docker push $DOCKER_PRIVATE_REPO/$IMAGE_NAME:latest

  push_tagged:
    docker:
    - image: circleci/golang:1.11-stretch-node
      environment:
        IMAGE_NAME: docker-webhook
    steps:
    - setup_remote_docker
    - attach_workspace:
        at: tmp
    - run:
        name: Load docker image
        command: |
          docker load -i tmp/image.tar

    - run:
        name: Login to artifactory
        command: |
          echo "$ARTIFACTORY_PASSWORD" | docker login -u $ARTIFACTORY_USER --password-stdin $DOCKER_PRIVATE_REPO

    - run:
        name: Tag image
        command: |
          docker tag docker-webhook:build $DOCKER_PRIVATE_REPO/$IMAGE_NAME:$(cat tmp/git-rev-tags.txt)

    - run:
        name: Push images
        command: |
          docker push $DOCKER_PRIVATE_REPO/$IMAGE_NAME:$(cat tmp/git-rev-tags.txt)

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - push_latest:
          requires:
            - build
          filters:
            branches:
              only: master
      - push_tagged:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
